version: "3.9"

services:
  media_container:
    build: .
    container_name: media_container
    depends_on:
      - minio
    volumes:
      - ./repo_media:/repo_media
      - ./:/app
    working_dir: /app
    environment:
      MEDIA_DIR: /repo_media
    command: python /app/server.py

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --address ":9000" --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - media_container
      - minio
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro

volumes:
  minio_data:
